---
## This is a simple task that uses [hammer to create a new domain][1] associated 
#  with our location and organization.  It also uses some facts gathered by
#  ansible.
#  The following variables are used and must be set elsewhere:
#  - sat
#      organization   # the organization used throughout
#      location       # the location used throughout
#
# [1]: https://access.redhat.com/documentation/en-us/red_hat_satellite/6.3/html/quick_start_guide/associating_objects_with_the_default_organization_and_location#creating_new_domain

- name: sat_domain| hammer> domain update
  command: >
    hammer domain update 
    --name "{{ ansible_domain }}" 
    --organizations "{{ sat.organization }}" 
    --locations "{{ sat.location }}" 
    --dns "{{ ansible_fqdn }}"
  tags: sat_domain